apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  labels:
    app: log-generator
spec:
  containers:
  - name: log-generator
    image: shreyjo07/log-gen:latest
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    env:
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: log-generator-secret
          key: OPENAI_API_KEY